### ISSUE TITLE
Where is project quick-box

### ISSUE THREAD

**Issue by clegall** [JMSDOnline/quick-box-assets#1]
The project has disappeared, he is abandoned ?

**Comment by JMSDOnline** [comment]
No, the project is still alive and well, although it has been ordained exclusivity rights to a provider that wishes to use it... exclusively. 

This means, the project is now closed-source and is not available for public modification and distribution.

Please note however, with the expressed permission of the party now holding rights to the project, there will be a public version available in the near future... we just need to work out some fine-grained details first.


Thank you for your interest and please stay tuned for the next publicly available release.

**Comment by clegall** [comment]
Ok 
I think I was too slow on this one .
We can talk in private?

**Comment by JMSDOnline** [comment]
Sure thing, you can contact me at jmsolodesigns@gmail[dot]com
